# ===============================
# Dataset Configuration
# ===============================

dataset:
  seed: 42
  total_target: 220000 # total number of training samples
  raw_data_dir: dataset/e-gmd-v1.0.0
  preprocessed_data_dir: dataset/processed
  train_test_val_split: [0.7, 0.2, 0.1] # train, test, val
  train_dir: dataset/processed/q_16/seg_64/train
  val_dir: dataset/processed/q_16/seg_64/val
  test_dir: dataset/processed/q_16/seg_64/test
  quantization: 16 # final should be 16 or 32
  segment_len: 64
  max_samples_per_file: 10
  inlcude_genre: false
  genres:
    - afrocuban
    - dance
    - funk
    - hiphop
    - jazz
    - latin
    - neworleans
    - pop
    - reggae
    - rock
    - soul
  pitch_groups:
    kick: [35, 36]
    snare: [38, 40]
    hh_closed: [42, 44]
    hh_open: [46]
    tom_low: [41, 43]
    tom_mid: [45, 47]
    tom_high: [48, 50]
    crash: [49, 57]
    ride: [51, 59]
  loudness_ranges: [0.0, 0.2, 0.4, 0.6, 0.8, 1.0]

# ===============================
# Model Configuration
# ===============================

model:
  small:
    hidden_dim: 128
    num_layers: 1
    dropout: 0.1
    token_embed_dim: 64
    pos_embed_dim: 4  
    genre_embed_dim: 8
  medium:
    hidden_dim: 256
    num_layers: 2
    dropout: 0.2
    token_embed_dim: 128
    pos_embed_dim: 8  
    genre_embed_dim: 8
  large:
    hidden_dim: 512
    num_layers: 3
    dropout: 0.3
    token_embed_dim: 256
    pos_embed_dim: 16  
    genre_embed_dim: 16

# ===============================
# Training Configuration
# ===============================

training:
  batch_size: 256
  epochs: 20
  learning_rate: 0.0005
  weight_decay: 0.0001
  teacher_forcing_start: 0.9
  teacher_forcing_end: 0.2
  checkpoint_dir: checkpoints



# ===============================
# Pipeline Configuration
# ===============================

pipeline:
  model: medium    #Options : [small, medium, large]
  preprocess: False
  train: False
  evaluate:
    enabled: False
    batch_size: 256
  plot: True
  inference: 
    enabled: True
    starting_sample: 12000
    generation_length: 258
    temperature: 0.9
    plot: True
    save_plot_filename: outputs/prediction_plot.png
    create_midi: True
    save_midi_filename: outputs/generated_genre.mid

