# ===============================
# dataset Configuration
# ===============================

dataset:
  quantization: 8 # final should be 16 or 32
  inlcude_genre: false
  genres:
    - funk
    - rock
    - jazz
    - latin
    - pop
    - hiphop
    - electronic
    - metal
    - reggae



