# ===============================
# Dataset Configuration
# ===============================

dataset:
  seed: 42
  total_target: 22000 # total number of training samples
  raw_data_dir: dataset/e-gmd-v1.0.0
  preprocessed_data_dir: dataset/processed
  train_test_split: 0.8
  quantization: 16 # final should be 16 or 32
  segment_len: 64
  max_samples_per_file: 10
  inlcude_genre: false
  genres:
    - afrocuban
    - dance
    - funk
    - hiphop
    - jazz
    - latin
    - neworleans
    - pop
    - reggae
    - rock
    - soul
  pitch_groups:
    kick: [35, 36]
    snare: [38, 40]
    hh_closed: [42, 44]
    hh_open: [46]
    tom_low: [41, 43]
    tom_mid: [45, 47]
    tom_high: [48, 50]
    crash: [49, 57]
    ride: [51, 59]
  loudness_ranges: [0.0, 0.2, 0.4, 0.6, 0.8, 1.0]

# ===============================
# Training Configuration
# ===============================

training:
  batch_size: 256
  epochs: 50
  learning_rate: 0.0005
  weight_decay: 0.0001
  teacher_forcing_start: 0.9
  teacher_forcing_end: 0.2
  checkpoint_dir: "checkpoints"
  checkpoint_interval: 5
  train_dir: dataset/processed/q_16/seg_64/train
  test_dir: dataset/processed/q_16/seg_64/test


# ===============================
# Pipeline Configuration
# ===============================

pipeline:
  model_name: "LSTM"    #Options : ["LSTM"]
  preprocess: False
  train: True
  tensor_board: True # ?
  evaluate: True # ?
  plot: True # ?
  inference: 
    enabled: True
    starting_sample: 0
    generation_length: 64
    temperature: 0.9
    plot: True

